production:
  server:
    port: 80
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: false
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    diskMemory: 2000000000
    ramMemory: 20000000

  data:
    apiEvaluating: "http://10.99.169.45/api/v1/evaluate"
    hostInflux: 10.109.241.183
    portInflux: 8086

  log:
    level: info
    file: "./logs/prod-logs.log" #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

development:
  server:
    port: 5050
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    diskMemory: 2000000000
    ramMemory: 20000000

  data:
    apiEvaluating: "http://localhost:5000/api/v1/evaluate"

  log:
    level: debug
    file: "./logs/dev-logs.log" #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

testing:
  server:
    port: 5000
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    diskMemory: 2000000000
    ramMemory: 20000000

  eslint:
    ignore:
      - ""
      - ""

  data:
    apiEvaluating: "http://localhost:5000/api/v1/evaluate"
  log:
    level: debug
    file: "./logs/test-logs.log" #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

