apiVersion: v1
kind: Service
metadata:
  name: api-translator
  labels:
    app: api-translator
spec:
  selector:
    app: api-translator
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  #   nodePort: 30502
  # type: "NodePort"
  type: "LoadBalancer"
  