apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-translator
  name: api-translator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-translator
    spec:
      containers:
      - name: api-translator
        image: api_translator_poetisa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

