apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apiTranslator
  name: apiTranslator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiTranslator
    spec:
      containers:
      - name: apiTranslator
        image: api_translator_poetisa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

